// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

// Triangle	 	 Tn=n(n+1)/2	1, 3, 6, 10, 15, ...
// Pentagonal	 Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
// Hexagonal	 Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.

// Find the next triangle number that is also pentagonal and hexagonal.

function isHexagonal(value)
{
    let delta = Math.sqrt(1 + (8*value));

    if (Math.floor(delta) !== delta)
        return false;

    let x = (1 + delta) / 4;

    return Math.floor(x) === Math.ceil(x);
}

function isTriangle(value)
{
    let delta = Math.sqrt(1 + 8*value);

    let x = (delta - 1)/2;
    
    return Math.floor(x) === Math.ceil(x);
}

function isPentagonal(value)
{
    let delta = Math.sqrt(1 + 24*value);

    if (Math.floor(delta) !== delta)
        return false;

    let x = (delta+1) / 6;

    return (Math.floor(x) === Math.ceil(x));
}

if (! isPentagonal(40755))
    throw "isPentagonal doesn't work";
if (! isTriangle(40755))
    throw "isTriangle doesn't work";
if (! isHexagonal(40755))
    throw "isHexagonal doesn't work";

let i = 40755;
while(true)
{
    i++;
    if (isTriangle(i) && isPentagonal(i) && isHexagonal(i))
        break;
}

console.log('Next triangle number that is also pentagonal and hexagonal is ' + i);