// Pentagon numbers
// Problem 44 
// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and 
// D = |Pk − Pj| is minimised; what is the value of D?

const RANGE = 2200;
/*
 2167,  1020 are a pair! |Pk − Pj| = 5482660
*/

function P(n)
{
    return (3*n*n - n)/2;
}

function reverseP(value)
{
    let delta = Math.sqrt(1 + 24*value);

    if (Math.floor(delta) !== delta)
        return -1;

    let x1 = (delta+1) / 6;

    if (x1 > 0 && Math.floor(x1) === x1)
    {
        return x1;
    }
    else
    {
        return -1;
    }
}

function test1()
{
    let s = '';
    for (let i = 1; i <= 10; i++)
        s += (P(i) + ' ');
    if (s !== '1 5 12 22 35 51 70 92 117 145 ')
        throw "Invalid";
}

function test2()
{
    let P4P7 = P(4) + P(7);
    let P7P4 = P(7) - P(4);
    
    if (reverseP(P4P7) !== 8)
        throw "Invalid";
    if (reverseP(P7P4) > 0)
        throw "Invalid";
}

test1();
test2();

for(let i = RANGE; i > 0; i--)
{
    let pi = P(i);
    for(let j = i-1; j > 0; j--)
    {
        let pj   = P(j);
        let plus = pi + pj;

        if (reverseP(plus) < 0)
            continue;

        let minus= pi - pj;
        if (minus < 0)
            minus = -minus;

        if (reverseP(minus) < 0)
            continue;
        
        console.log(i + ", " + j + " are a pair! |Pk − Pj| = " + minus);
    }
}

console.log("DONE");